// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package validator

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Validator            protoreflect.MessageDescriptor
	fd_Validator_id         protoreflect.FieldDescriptor
	fd_Validator_name       protoreflect.FieldDescriptor
	fd_Validator_category   protoreflect.FieldDescriptor
	fd_Validator_timestamp  protoreflect.FieldDescriptor
	fd_Validator_ogcAddress protoreflect.FieldDescriptor
	fd_Validator_kycInfo    protoreflect.FieldDescriptor
	fd_Validator_options    protoreflect.FieldDescriptor
	fd_Validator_status     protoreflect.FieldDescriptor
)

func init() {
	file_optimizeglobalcoin_validator_validator_proto_init()
	md_Validator = File_optimizeglobalcoin_validator_validator_proto.Messages().ByName("Validator")
	fd_Validator_id = md_Validator.Fields().ByName("id")
	fd_Validator_name = md_Validator.Fields().ByName("name")
	fd_Validator_category = md_Validator.Fields().ByName("category")
	fd_Validator_timestamp = md_Validator.Fields().ByName("timestamp")
	fd_Validator_ogcAddress = md_Validator.Fields().ByName("ogcAddress")
	fd_Validator_kycInfo = md_Validator.Fields().ByName("kycInfo")
	fd_Validator_options = md_Validator.Fields().ByName("options")
	fd_Validator_status = md_Validator.Fields().ByName("status")
}

var _ protoreflect.Message = (*fastReflection_Validator)(nil)

type fastReflection_Validator Validator

func (x *Validator) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Validator)(x)
}

func (x *Validator) slowProtoReflect() protoreflect.Message {
	mi := &file_optimizeglobalcoin_validator_validator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Validator_messageType fastReflection_Validator_messageType
var _ protoreflect.MessageType = fastReflection_Validator_messageType{}

type fastReflection_Validator_messageType struct{}

func (x fastReflection_Validator_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Validator)(nil)
}
func (x fastReflection_Validator_messageType) New() protoreflect.Message {
	return new(fastReflection_Validator)
}
func (x fastReflection_Validator_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Validator
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Validator) Descriptor() protoreflect.MessageDescriptor {
	return md_Validator
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Validator) Type() protoreflect.MessageType {
	return _fastReflection_Validator_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Validator) New() protoreflect.Message {
	return new(fastReflection_Validator)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Validator) Interface() protoreflect.ProtoMessage {
	return (*Validator)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Validator) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Validator_id, value) {
			return
		}
	}
	if x.Name != "" {
		value := protoreflect.ValueOfString(x.Name)
		if !f(fd_Validator_name, value) {
			return
		}
	}
	if x.Category != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Category))
		if !f(fd_Validator_category, value) {
			return
		}
	}
	if x.Timestamp != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Timestamp)
		if !f(fd_Validator_timestamp, value) {
			return
		}
	}
	if x.OgcAddress != "" {
		value := protoreflect.ValueOfString(x.OgcAddress)
		if !f(fd_Validator_ogcAddress, value) {
			return
		}
	}
	if x.KycInfo != "" {
		value := protoreflect.ValueOfString(x.KycInfo)
		if !f(fd_Validator_kycInfo, value) {
			return
		}
	}
	if x.Options != "" {
		value := protoreflect.ValueOfString(x.Options)
		if !f(fd_Validator_options, value) {
			return
		}
	}
	if x.Status != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Status))
		if !f(fd_Validator_status, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Validator) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "optimizeglobalcoin.validator.Validator.id":
		return x.Id != uint64(0)
	case "optimizeglobalcoin.validator.Validator.name":
		return x.Name != ""
	case "optimizeglobalcoin.validator.Validator.category":
		return x.Category != 0
	case "optimizeglobalcoin.validator.Validator.timestamp":
		return x.Timestamp != uint64(0)
	case "optimizeglobalcoin.validator.Validator.ogcAddress":
		return x.OgcAddress != ""
	case "optimizeglobalcoin.validator.Validator.kycInfo":
		return x.KycInfo != ""
	case "optimizeglobalcoin.validator.Validator.options":
		return x.Options != ""
	case "optimizeglobalcoin.validator.Validator.status":
		return x.Status != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.validator.Validator"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.validator.Validator does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Validator) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "optimizeglobalcoin.validator.Validator.id":
		x.Id = uint64(0)
	case "optimizeglobalcoin.validator.Validator.name":
		x.Name = ""
	case "optimizeglobalcoin.validator.Validator.category":
		x.Category = 0
	case "optimizeglobalcoin.validator.Validator.timestamp":
		x.Timestamp = uint64(0)
	case "optimizeglobalcoin.validator.Validator.ogcAddress":
		x.OgcAddress = ""
	case "optimizeglobalcoin.validator.Validator.kycInfo":
		x.KycInfo = ""
	case "optimizeglobalcoin.validator.Validator.options":
		x.Options = ""
	case "optimizeglobalcoin.validator.Validator.status":
		x.Status = 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.validator.Validator"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.validator.Validator does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Validator) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "optimizeglobalcoin.validator.Validator.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "optimizeglobalcoin.validator.Validator.name":
		value := x.Name
		return protoreflect.ValueOfString(value)
	case "optimizeglobalcoin.validator.Validator.category":
		value := x.Category
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "optimizeglobalcoin.validator.Validator.timestamp":
		value := x.Timestamp
		return protoreflect.ValueOfUint64(value)
	case "optimizeglobalcoin.validator.Validator.ogcAddress":
		value := x.OgcAddress
		return protoreflect.ValueOfString(value)
	case "optimizeglobalcoin.validator.Validator.kycInfo":
		value := x.KycInfo
		return protoreflect.ValueOfString(value)
	case "optimizeglobalcoin.validator.Validator.options":
		value := x.Options
		return protoreflect.ValueOfString(value)
	case "optimizeglobalcoin.validator.Validator.status":
		value := x.Status
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.validator.Validator"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.validator.Validator does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Validator) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "optimizeglobalcoin.validator.Validator.id":
		x.Id = value.Uint()
	case "optimizeglobalcoin.validator.Validator.name":
		x.Name = value.Interface().(string)
	case "optimizeglobalcoin.validator.Validator.category":
		x.Category = (ValidatorType)(value.Enum())
	case "optimizeglobalcoin.validator.Validator.timestamp":
		x.Timestamp = value.Uint()
	case "optimizeglobalcoin.validator.Validator.ogcAddress":
		x.OgcAddress = value.Interface().(string)
	case "optimizeglobalcoin.validator.Validator.kycInfo":
		x.KycInfo = value.Interface().(string)
	case "optimizeglobalcoin.validator.Validator.options":
		x.Options = value.Interface().(string)
	case "optimizeglobalcoin.validator.Validator.status":
		x.Status = (ValidatorStatus)(value.Enum())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.validator.Validator"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.validator.Validator does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Validator) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "optimizeglobalcoin.validator.Validator.id":
		panic(fmt.Errorf("field id of message optimizeglobalcoin.validator.Validator is not mutable"))
	case "optimizeglobalcoin.validator.Validator.name":
		panic(fmt.Errorf("field name of message optimizeglobalcoin.validator.Validator is not mutable"))
	case "optimizeglobalcoin.validator.Validator.category":
		panic(fmt.Errorf("field category of message optimizeglobalcoin.validator.Validator is not mutable"))
	case "optimizeglobalcoin.validator.Validator.timestamp":
		panic(fmt.Errorf("field timestamp of message optimizeglobalcoin.validator.Validator is not mutable"))
	case "optimizeglobalcoin.validator.Validator.ogcAddress":
		panic(fmt.Errorf("field ogcAddress of message optimizeglobalcoin.validator.Validator is not mutable"))
	case "optimizeglobalcoin.validator.Validator.kycInfo":
		panic(fmt.Errorf("field kycInfo of message optimizeglobalcoin.validator.Validator is not mutable"))
	case "optimizeglobalcoin.validator.Validator.options":
		panic(fmt.Errorf("field options of message optimizeglobalcoin.validator.Validator is not mutable"))
	case "optimizeglobalcoin.validator.Validator.status":
		panic(fmt.Errorf("field status of message optimizeglobalcoin.validator.Validator is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.validator.Validator"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.validator.Validator does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Validator) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "optimizeglobalcoin.validator.Validator.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "optimizeglobalcoin.validator.Validator.name":
		return protoreflect.ValueOfString("")
	case "optimizeglobalcoin.validator.Validator.category":
		return protoreflect.ValueOfEnum(0)
	case "optimizeglobalcoin.validator.Validator.timestamp":
		return protoreflect.ValueOfUint64(uint64(0))
	case "optimizeglobalcoin.validator.Validator.ogcAddress":
		return protoreflect.ValueOfString("")
	case "optimizeglobalcoin.validator.Validator.kycInfo":
		return protoreflect.ValueOfString("")
	case "optimizeglobalcoin.validator.Validator.options":
		return protoreflect.ValueOfString("")
	case "optimizeglobalcoin.validator.Validator.status":
		return protoreflect.ValueOfEnum(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.validator.Validator"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.validator.Validator does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Validator) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in optimizeglobalcoin.validator.Validator", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Validator) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Validator) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Validator) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Validator) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Validator)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Name)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Category != 0 {
			n += 1 + runtime.Sov(uint64(x.Category))
		}
		if x.Timestamp != 0 {
			n += 1 + runtime.Sov(uint64(x.Timestamp))
		}
		l = len(x.OgcAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.KycInfo)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Options)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Status != 0 {
			n += 1 + runtime.Sov(uint64(x.Status))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Validator)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Status != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Status))
			i--
			dAtA[i] = 0x40
		}
		if len(x.Options) > 0 {
			i -= len(x.Options)
			copy(dAtA[i:], x.Options)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Options)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.KycInfo) > 0 {
			i -= len(x.KycInfo)
			copy(dAtA[i:], x.KycInfo)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.KycInfo)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.OgcAddress) > 0 {
			i -= len(x.OgcAddress)
			copy(dAtA[i:], x.OgcAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OgcAddress)))
			i--
			dAtA[i] = 0x2a
		}
		if x.Timestamp != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Timestamp))
			i--
			dAtA[i] = 0x20
		}
		if x.Category != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Category))
			i--
			dAtA[i] = 0x18
		}
		if len(x.Name) > 0 {
			i -= len(x.Name)
			copy(dAtA[i:], x.Name)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Name)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Validator)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Validator: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Name = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
				}
				x.Category = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Category |= ValidatorType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
				}
				x.Timestamp = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Timestamp |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OgcAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OgcAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field KycInfo", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.KycInfo = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Options", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Options = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				x.Status = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Status |= ValidatorStatus(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: optimizeglobalcoin/validator/validator.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatorType int32

const (
	ValidatorType_UNRECOGNIZED   ValidatorType = 0
	ValidatorType_PROTECTORS     ValidatorType = 1
	ValidatorType_CONFIRMERS     ValidatorType = 2
	ValidatorType_AUDITORS       ValidatorType = 3
	ValidatorType_LAWYERS        ValidatorType = 4
	ValidatorType_ASSET_MANAGERS ValidatorType = 5
	ValidatorType_OTHER          ValidatorType = 6
)

// Enum value maps for ValidatorType.
var (
	ValidatorType_name = map[int32]string{
		0: "UNRECOGNIZED",
		1: "PROTECTORS",
		2: "CONFIRMERS",
		3: "AUDITORS",
		4: "LAWYERS",
		5: "ASSET_MANAGERS",
		6: "OTHER",
	}
	ValidatorType_value = map[string]int32{
		"UNRECOGNIZED":   0,
		"PROTECTORS":     1,
		"CONFIRMERS":     2,
		"AUDITORS":       3,
		"LAWYERS":        4,
		"ASSET_MANAGERS": 5,
		"OTHER":          6,
	}
)

func (x ValidatorType) Enum() *ValidatorType {
	p := new(ValidatorType)
	*p = x
	return p
}

func (x ValidatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizeglobalcoin_validator_validator_proto_enumTypes[0].Descriptor()
}

func (ValidatorType) Type() protoreflect.EnumType {
	return &file_optimizeglobalcoin_validator_validator_proto_enumTypes[0]
}

func (x ValidatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidatorType.Descriptor instead.
func (ValidatorType) EnumDescriptor() ([]byte, []int) {
	return file_optimizeglobalcoin_validator_validator_proto_rawDescGZIP(), []int{0}
}

type ValidatorStatus int32

const (
	ValidatorStatus_ACTIVE   ValidatorStatus = 0
	ValidatorStatus_INACTIVE ValidatorStatus = 1
)

// Enum value maps for ValidatorStatus.
var (
	ValidatorStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "INACTIVE",
	}
	ValidatorStatus_value = map[string]int32{
		"ACTIVE":   0,
		"INACTIVE": 1,
	}
)

func (x ValidatorStatus) Enum() *ValidatorStatus {
	p := new(ValidatorStatus)
	*p = x
	return p
}

func (x ValidatorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidatorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizeglobalcoin_validator_validator_proto_enumTypes[1].Descriptor()
}

func (ValidatorStatus) Type() protoreflect.EnumType {
	return &file_optimizeglobalcoin_validator_validator_proto_enumTypes[1]
}

func (x ValidatorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidatorStatus.Descriptor instead.
func (ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizeglobalcoin_validator_validator_proto_rawDescGZIP(), []int{1}
}

type Validator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category   ValidatorType   `protobuf:"varint,3,opt,name=category,proto3,enum=optimizeglobalcoin.validator.ValidatorType" json:"category,omitempty"`
	Timestamp  uint64          `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OgcAddress string          `protobuf:"bytes,5,opt,name=ogcAddress,proto3" json:"ogcAddress,omitempty"`
	KycInfo    string          `protobuf:"bytes,6,opt,name=kycInfo,proto3" json:"kycInfo,omitempty"`
	Options    string          `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`
	Status     ValidatorStatus `protobuf:"varint,8,opt,name=status,proto3,enum=optimizeglobalcoin.validator.ValidatorStatus" json:"status,omitempty"`
}

func (x *Validator) Reset() {
	*x = Validator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optimizeglobalcoin_validator_validator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_optimizeglobalcoin_validator_validator_proto_rawDescGZIP(), []int{0}
}

func (x *Validator) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Validator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Validator) GetCategory() ValidatorType {
	if x != nil {
		return x.Category
	}
	return ValidatorType_UNRECOGNIZED
}

func (x *Validator) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Validator) GetOgcAddress() string {
	if x != nil {
		return x.OgcAddress
	}
	return ""
}

func (x *Validator) GetKycInfo() string {
	if x != nil {
		return x.KycInfo
	}
	return ""
}

func (x *Validator) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *Validator) GetStatus() ValidatorStatus {
	if x != nil {
		return x.Status
	}
	return ValidatorStatus_ACTIVE
}

var File_optimizeglobalcoin_validator_validator_proto protoreflect.FileDescriptor

var file_optimizeglobalcoin_validator_validator_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xb1, 0x02, 0x0a,
	0x09, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x47,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2b, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x67, 0x63, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x67, 0x63, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x79, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x79, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x45, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2a, 0x7b, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x52, 0x45, 0x43, 0x4f, 0x47, 0x4e, 0x49, 0x5a, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x54, 0x45, 0x43, 0x54, 0x4f, 0x52,
	0x53, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x45, 0x52,
	0x53, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x55, 0x44, 0x49, 0x54, 0x4f, 0x52, 0x53, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x41, 0x57, 0x59, 0x45, 0x52, 0x53, 0x10, 0x04, 0x12, 0x12,
	0x0a, 0x0e, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x53,
	0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x06, 0x2a, 0x2b, 0x0a,
	0x0f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x42, 0xf8, 0x01, 0x0a, 0x20, 0x63,
	0x6f, 0x6d, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x42,
	0x0e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x33, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69,
	0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0xa2, 0x02, 0x03, 0x4f, 0x56, 0x58, 0xaa, 0x02, 0x1c, 0x4f,
	0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69,
	0x6e, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0xca, 0x02, 0x1c, 0x4f, 0x70,
	0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e,
	0x5c, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0xe2, 0x02, 0x28, 0x4f, 0x70, 0x74,
	0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x5c,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x1d, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65,
	0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x3a, 0x3a, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_optimizeglobalcoin_validator_validator_proto_rawDescOnce sync.Once
	file_optimizeglobalcoin_validator_validator_proto_rawDescData = file_optimizeglobalcoin_validator_validator_proto_rawDesc
)

func file_optimizeglobalcoin_validator_validator_proto_rawDescGZIP() []byte {
	file_optimizeglobalcoin_validator_validator_proto_rawDescOnce.Do(func() {
		file_optimizeglobalcoin_validator_validator_proto_rawDescData = protoimpl.X.CompressGZIP(file_optimizeglobalcoin_validator_validator_proto_rawDescData)
	})
	return file_optimizeglobalcoin_validator_validator_proto_rawDescData
}

var file_optimizeglobalcoin_validator_validator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_optimizeglobalcoin_validator_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_optimizeglobalcoin_validator_validator_proto_goTypes = []interface{}{
	(ValidatorType)(0),   // 0: optimizeglobalcoin.validator.ValidatorType
	(ValidatorStatus)(0), // 1: optimizeglobalcoin.validator.ValidatorStatus
	(*Validator)(nil),    // 2: optimizeglobalcoin.validator.Validator
}
var file_optimizeglobalcoin_validator_validator_proto_depIdxs = []int32{
	0, // 0: optimizeglobalcoin.validator.Validator.category:type_name -> optimizeglobalcoin.validator.ValidatorType
	1, // 1: optimizeglobalcoin.validator.Validator.status:type_name -> optimizeglobalcoin.validator.ValidatorStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_optimizeglobalcoin_validator_validator_proto_init() }
func file_optimizeglobalcoin_validator_validator_proto_init() {
	if File_optimizeglobalcoin_validator_validator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_optimizeglobalcoin_validator_validator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_optimizeglobalcoin_validator_validator_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_optimizeglobalcoin_validator_validator_proto_goTypes,
		DependencyIndexes: file_optimizeglobalcoin_validator_validator_proto_depIdxs,
		EnumInfos:         file_optimizeglobalcoin_validator_validator_proto_enumTypes,
		MessageInfos:      file_optimizeglobalcoin_validator_validator_proto_msgTypes,
	}.Build()
	File_optimizeglobalcoin_validator_validator_proto = out.File
	file_optimizeglobalcoin_validator_validator_proto_rawDesc = nil
	file_optimizeglobalcoin_validator_validator_proto_goTypes = nil
	file_optimizeglobalcoin_validator_validator_proto_depIdxs = nil
}
