// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package oconsensus

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_Payload            protoreflect.MessageDescriptor
	fd_Payload_voter      protoreflect.FieldDescriptor
	fd_Payload_result     protoreflect.FieldDescriptor
	fd_Payload_value      protoreflect.FieldDescriptor
	fd_Payload_err_reason protoreflect.FieldDescriptor
)

func init() {
	file_optimizeglobalcoin_oconsensus_consensus_payload_proto_init()
	md_Payload = File_optimizeglobalcoin_oconsensus_consensus_payload_proto.Messages().ByName("Payload")
	fd_Payload_voter = md_Payload.Fields().ByName("voter")
	fd_Payload_result = md_Payload.Fields().ByName("result")
	fd_Payload_value = md_Payload.Fields().ByName("value")
	fd_Payload_err_reason = md_Payload.Fields().ByName("err_reason")
}

var _ protoreflect.Message = (*fastReflection_Payload)(nil)

type fastReflection_Payload Payload

func (x *Payload) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Payload)(x)
}

func (x *Payload) slowProtoReflect() protoreflect.Message {
	mi := &file_optimizeglobalcoin_oconsensus_consensus_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Payload_messageType fastReflection_Payload_messageType
var _ protoreflect.MessageType = fastReflection_Payload_messageType{}

type fastReflection_Payload_messageType struct{}

func (x fastReflection_Payload_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Payload)(nil)
}
func (x fastReflection_Payload_messageType) New() protoreflect.Message {
	return new(fastReflection_Payload)
}
func (x fastReflection_Payload_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Payload
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Payload) Descriptor() protoreflect.MessageDescriptor {
	return md_Payload
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Payload) Type() protoreflect.MessageType {
	return _fastReflection_Payload_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Payload) New() protoreflect.Message {
	return new(fastReflection_Payload)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Payload) Interface() protoreflect.ProtoMessage {
	return (*Payload)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Payload) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Voter != "" {
		value := protoreflect.ValueOfString(x.Voter)
		if !f(fd_Payload_voter, value) {
			return
		}
	}
	if x.Result != false {
		value := protoreflect.ValueOfBool(x.Result)
		if !f(fd_Payload_result, value) {
			return
		}
	}
	if x.Value != "" {
		value := protoreflect.ValueOfString(x.Value)
		if !f(fd_Payload_value, value) {
			return
		}
	}
	if x.ErrReason != "" {
		value := protoreflect.ValueOfString(x.ErrReason)
		if !f(fd_Payload_err_reason, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Payload) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.Payload.voter":
		return x.Voter != ""
	case "optimizeglobalcoin.oconsensus.Payload.result":
		return x.Result != false
	case "optimizeglobalcoin.oconsensus.Payload.value":
		return x.Value != ""
	case "optimizeglobalcoin.oconsensus.Payload.err_reason":
		return x.ErrReason != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.Payload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.Payload does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Payload) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.Payload.voter":
		x.Voter = ""
	case "optimizeglobalcoin.oconsensus.Payload.result":
		x.Result = false
	case "optimizeglobalcoin.oconsensus.Payload.value":
		x.Value = ""
	case "optimizeglobalcoin.oconsensus.Payload.err_reason":
		x.ErrReason = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.Payload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.Payload does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Payload) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "optimizeglobalcoin.oconsensus.Payload.voter":
		value := x.Voter
		return protoreflect.ValueOfString(value)
	case "optimizeglobalcoin.oconsensus.Payload.result":
		value := x.Result
		return protoreflect.ValueOfBool(value)
	case "optimizeglobalcoin.oconsensus.Payload.value":
		value := x.Value
		return protoreflect.ValueOfString(value)
	case "optimizeglobalcoin.oconsensus.Payload.err_reason":
		value := x.ErrReason
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.Payload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.Payload does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Payload) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.Payload.voter":
		x.Voter = value.Interface().(string)
	case "optimizeglobalcoin.oconsensus.Payload.result":
		x.Result = value.Bool()
	case "optimizeglobalcoin.oconsensus.Payload.value":
		x.Value = value.Interface().(string)
	case "optimizeglobalcoin.oconsensus.Payload.err_reason":
		x.ErrReason = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.Payload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.Payload does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Payload) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.Payload.voter":
		panic(fmt.Errorf("field voter of message optimizeglobalcoin.oconsensus.Payload is not mutable"))
	case "optimizeglobalcoin.oconsensus.Payload.result":
		panic(fmt.Errorf("field result of message optimizeglobalcoin.oconsensus.Payload is not mutable"))
	case "optimizeglobalcoin.oconsensus.Payload.value":
		panic(fmt.Errorf("field value of message optimizeglobalcoin.oconsensus.Payload is not mutable"))
	case "optimizeglobalcoin.oconsensus.Payload.err_reason":
		panic(fmt.Errorf("field err_reason of message optimizeglobalcoin.oconsensus.Payload is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.Payload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.Payload does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Payload) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.Payload.voter":
		return protoreflect.ValueOfString("")
	case "optimizeglobalcoin.oconsensus.Payload.result":
		return protoreflect.ValueOfBool(false)
	case "optimizeglobalcoin.oconsensus.Payload.value":
		return protoreflect.ValueOfString("")
	case "optimizeglobalcoin.oconsensus.Payload.err_reason":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.Payload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.Payload does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Payload) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in optimizeglobalcoin.oconsensus.Payload", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Payload) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Payload) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Payload) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Payload) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Payload)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Voter)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Result {
			n += 2
		}
		l = len(x.Value)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ErrReason)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Payload)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ErrReason) > 0 {
			i -= len(x.ErrReason)
			copy(dAtA[i:], x.ErrReason)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ErrReason)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Value) > 0 {
			i -= len(x.Value)
			copy(dAtA[i:], x.Value)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Value)))
			i--
			dAtA[i] = 0x1a
		}
		if x.Result {
			i--
			if x.Result {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x10
		}
		if len(x.Voter) > 0 {
			i -= len(x.Voter)
			copy(dAtA[i:], x.Voter)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Voter)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Payload)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Payload: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Payload: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Voter = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Result = bool(v != 0)
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Value = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ErrReason", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ErrReason = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_ConsensusPayload_1_list)(nil)

type _ConsensusPayload_1_list struct {
	list *[]*Payload
}

func (x *_ConsensusPayload_1_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_ConsensusPayload_1_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_ConsensusPayload_1_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*Payload)
	(*x.list)[i] = concreteValue
}

func (x *_ConsensusPayload_1_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*Payload)
	*x.list = append(*x.list, concreteValue)
}

func (x *_ConsensusPayload_1_list) AppendMutable() protoreflect.Value {
	v := new(Payload)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_ConsensusPayload_1_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_ConsensusPayload_1_list) NewElement() protoreflect.Value {
	v := new(Payload)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_ConsensusPayload_1_list) IsValid() bool {
	return x.list != nil
}

var (
	md_ConsensusPayload          protoreflect.MessageDescriptor
	fd_ConsensusPayload_payloads protoreflect.FieldDescriptor
)

func init() {
	file_optimizeglobalcoin_oconsensus_consensus_payload_proto_init()
	md_ConsensusPayload = File_optimizeglobalcoin_oconsensus_consensus_payload_proto.Messages().ByName("ConsensusPayload")
	fd_ConsensusPayload_payloads = md_ConsensusPayload.Fields().ByName("payloads")
}

var _ protoreflect.Message = (*fastReflection_ConsensusPayload)(nil)

type fastReflection_ConsensusPayload ConsensusPayload

func (x *ConsensusPayload) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ConsensusPayload)(x)
}

func (x *ConsensusPayload) slowProtoReflect() protoreflect.Message {
	mi := &file_optimizeglobalcoin_oconsensus_consensus_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ConsensusPayload_messageType fastReflection_ConsensusPayload_messageType
var _ protoreflect.MessageType = fastReflection_ConsensusPayload_messageType{}

type fastReflection_ConsensusPayload_messageType struct{}

func (x fastReflection_ConsensusPayload_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ConsensusPayload)(nil)
}
func (x fastReflection_ConsensusPayload_messageType) New() protoreflect.Message {
	return new(fastReflection_ConsensusPayload)
}
func (x fastReflection_ConsensusPayload_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ConsensusPayload
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ConsensusPayload) Descriptor() protoreflect.MessageDescriptor {
	return md_ConsensusPayload
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ConsensusPayload) Type() protoreflect.MessageType {
	return _fastReflection_ConsensusPayload_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ConsensusPayload) New() protoreflect.Message {
	return new(fastReflection_ConsensusPayload)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ConsensusPayload) Interface() protoreflect.ProtoMessage {
	return (*ConsensusPayload)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ConsensusPayload) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.Payloads) != 0 {
		value := protoreflect.ValueOfList(&_ConsensusPayload_1_list{list: &x.Payloads})
		if !f(fd_ConsensusPayload_payloads, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ConsensusPayload) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.ConsensusPayload.payloads":
		return len(x.Payloads) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.ConsensusPayload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.ConsensusPayload does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ConsensusPayload) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.ConsensusPayload.payloads":
		x.Payloads = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.ConsensusPayload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.ConsensusPayload does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ConsensusPayload) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "optimizeglobalcoin.oconsensus.ConsensusPayload.payloads":
		if len(x.Payloads) == 0 {
			return protoreflect.ValueOfList(&_ConsensusPayload_1_list{})
		}
		listValue := &_ConsensusPayload_1_list{list: &x.Payloads}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.ConsensusPayload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.ConsensusPayload does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ConsensusPayload) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.ConsensusPayload.payloads":
		lv := value.List()
		clv := lv.(*_ConsensusPayload_1_list)
		x.Payloads = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.ConsensusPayload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.ConsensusPayload does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ConsensusPayload) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.ConsensusPayload.payloads":
		if x.Payloads == nil {
			x.Payloads = []*Payload{}
		}
		value := &_ConsensusPayload_1_list{list: &x.Payloads}
		return protoreflect.ValueOfList(value)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.ConsensusPayload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.ConsensusPayload does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ConsensusPayload) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "optimizeglobalcoin.oconsensus.ConsensusPayload.payloads":
		list := []*Payload{}
		return protoreflect.ValueOfList(&_ConsensusPayload_1_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: optimizeglobalcoin.oconsensus.ConsensusPayload"))
		}
		panic(fmt.Errorf("message optimizeglobalcoin.oconsensus.ConsensusPayload does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ConsensusPayload) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in optimizeglobalcoin.oconsensus.ConsensusPayload", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ConsensusPayload) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ConsensusPayload) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ConsensusPayload) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ConsensusPayload) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ConsensusPayload)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.Payloads) > 0 {
			for _, e := range x.Payloads {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ConsensusPayload)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Payloads) > 0 {
			for iNdEx := len(x.Payloads) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Payloads[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0xa
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ConsensusPayload)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ConsensusPayload: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ConsensusPayload: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Payloads", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Payloads = append(x.Payloads, &Payload{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Payloads[len(x.Payloads)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: optimizeglobalcoin/oconsensus/consensus_payload.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload defines the necessary items for running a consensus algorithm
type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voter     string `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`                          // ob address that submitted the vote
	Result    bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`                       // success or fail
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                          // value to be evaluated
	ErrReason string `protobuf:"bytes,4,opt,name=err_reason,json=errReason,proto3" json:"err_reason,omitempty"` // if fails, attach error reason
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optimizeglobalcoin_oconsensus_consensus_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *Payload) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *Payload) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Payload) GetErrReason() string {
	if x != nil {
		return x.ErrReason
	}
	return ""
}

// ConsensusPayload defines the payload for the consensus algorithm.
type ConsensusPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payloads []*Payload `protobuf:"bytes,1,rep,name=payloads,proto3" json:"payloads,omitempty"`
}

func (x *ConsensusPayload) Reset() {
	*x = ConsensusPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optimizeglobalcoin_oconsensus_consensus_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusPayload) ProtoMessage() {}

// Deprecated: Use ConsensusPayload.ProtoReflect.Descriptor instead.
func (*ConsensusPayload) Descriptor() ([]byte, []int) {
	return file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusPayload) GetPayloads() []*Payload {
	if x != nil {
		return x.Payloads
	}
	return nil
}

var File_optimizeglobalcoin_oconsensus_consensus_payload_proto protoreflect.FileDescriptor

var file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDesc = []byte{
	0x0a, 0x35, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x6f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f,
	0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a,
	0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x6f, 0x63, 0x6f, 0x6e,
	0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x07,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x72, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x10, 0x43, 0x6f,
	0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x48,
	0x0a, 0x08, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x6f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x08,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x42, 0x85, 0x02, 0x0a, 0x21, 0x63, 0x6f, 0x6d,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63,
	0x6f, 0x69, 0x6e, 0x2e, 0x6f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x42, 0x15,
	0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x34, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a,
	0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f,
	0x69, 0x6e, 0x2f, 0x6f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0xa2, 0x02, 0x03,
	0x4f, 0x4f, 0x58, 0xaa, 0x02, 0x1d, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x4f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e,
	0x73, 0x75, 0x73, 0xca, 0x02, 0x1d, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x5c, 0x4f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e,
	0x73, 0x75, 0x73, 0xe2, 0x02, 0x29, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x63, 0x6f, 0x69, 0x6e, 0x5c, 0x4f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e,
	0x73, 0x75, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x1e, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x63, 0x6f, 0x69, 0x6e, 0x3a, 0x3a, 0x4f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescOnce sync.Once
	file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescData = file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDesc
)

func file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescGZIP() []byte {
	file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescOnce.Do(func() {
		file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescData)
	})
	return file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDescData
}

var file_optimizeglobalcoin_oconsensus_consensus_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_optimizeglobalcoin_oconsensus_consensus_payload_proto_goTypes = []interface{}{
	(*Payload)(nil),          // 0: optimizeglobalcoin.oconsensus.Payload
	(*ConsensusPayload)(nil), // 1: optimizeglobalcoin.oconsensus.ConsensusPayload
}
var file_optimizeglobalcoin_oconsensus_consensus_payload_proto_depIdxs = []int32{
	0, // 0: optimizeglobalcoin.oconsensus.ConsensusPayload.payloads:type_name -> optimizeglobalcoin.oconsensus.Payload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_optimizeglobalcoin_oconsensus_consensus_payload_proto_init() }
func file_optimizeglobalcoin_oconsensus_consensus_payload_proto_init() {
	if File_optimizeglobalcoin_oconsensus_consensus_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_optimizeglobalcoin_oconsensus_consensus_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_optimizeglobalcoin_oconsensus_consensus_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsensusPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_optimizeglobalcoin_oconsensus_consensus_payload_proto_goTypes,
		DependencyIndexes: file_optimizeglobalcoin_oconsensus_consensus_payload_proto_depIdxs,
		MessageInfos:      file_optimizeglobalcoin_oconsensus_consensus_payload_proto_msgTypes,
	}.Build()
	File_optimizeglobalcoin_oconsensus_consensus_payload_proto = out.File
	file_optimizeglobalcoin_oconsensus_consensus_payload_proto_rawDesc = nil
	file_optimizeglobalcoin_oconsensus_consensus_payload_proto_goTypes = nil
	file_optimizeglobalcoin_oconsensus_consensus_payload_proto_depIdxs = nil
}
